name: Build

on:
  push:
  pull_request:

jobs:
  build:
    name: Build

    runs-on: ${{ matrix.os }}
    env:
      GOPATH: ${{ github.workspace }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - name: Setup repo
        uses: actions/checkout@v2
        with:
          submodules: true
          path: './src/github.com/useverto/desktop'

      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: 14.x

      - name: Setup go
        uses: actions/setup-go@v2
      
      - name: Install dependencies
        working-directory: ./src/github.com/useverto/desktop/verto
        run: |
          npm i -g yarn
          yarn

      - name: Build website source
        working-directory: ./src/github.com/useverto/desktop/verto
        run: | 
           yarn build
           yarn export

      - name: Install libwebkit
        if: startsWith(matrix.os, 'ubuntu')
        run: |
          sudo apt-get update
          sudo apt-get install libwebkit2gtk-4.0-dev
          
      
      - name: Install statik
        run: | 
          go get github.com/rakyll/statik
          go get github.com/webview/webview
          
      
      - name: Compile website
        run: go run ./src/github.com/rakyll/statik/statik.go -src=${{ github.workspace }}/src/github.com/useverto/desktop/verto/__sapper__/export
      
      - name: Build desktop app
        run: go build ${{ github.workspace }}/src/github.com/useverto/desktop/desktop.go

