name: Build

on:
  push:
  pull_request:

jobs:
  build:
    name: Build

    runs-on: ${{ matrix.os }}
    env:
      GOPATH: ${{ github.workspace }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      - name: Setup repo
        uses: actions/checkout@v2
        with:
          submodules: true
          path: "./src/github.com/useverto/desktop"

      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: 14.x

      - name: Setup go
        uses: actions/setup-go@v2

      - name: Install dependencies
        working-directory: ./src/github.com/useverto/desktop/verto
        run: |
          npm i -g yarn
          yarn

      - name: Build website source
        working-directory: ./src/github.com/useverto/desktop/verto
        run: |
          yarn build
          yarn export

      - name: Install libwebkit
        if: startsWith(matrix.os, 'ubuntu')
        run: |
          sudo apt-get update
          sudo apt-get install libwebkit2gtk-4.0-dev
          curl -L https://raw.githubusercontent.com/mh-cbon/latest/master/install.sh | GH=mh-cbon/go-bin-deb sh -xe

      - name: Install Wix Toolset 3
        if: startsWith(matrix.os, 'windows')
        run: |
          curl -OLS https://github.com/wixtoolset/wix3/releases/download/wix3111rtm/wix311.exe
          .\wix311.exe /install /quiet /norestart
        
      - name: Install Go deps
        run: |
          go get github.com/rakyll/statik github.com/mitchellh/go-homedir github.com/tcnksm/go-latest github.com/kardianos/osext github.com/fsnotify/fsnotify

      - name: Compile website
        run: go run ./src/github.com/useverto/desktop/fs/embed.go -src=${{ github.workspace }}/src/github.com/useverto/desktop/verto/__sapper__/export --dest=${{ github.workspace }}/src/github.com/useverto/desktop

      - name: Build Linux Deb
        working-directory: ./src/github.com/useverto/desktop
        if: startsWith(matrix.os, 'ubuntu')
        run: |
          go build .
          sh ./tools/create_deb.sh

      - name: Build OSX app
        working-directory: ./src/github.com/useverto/desktop
        if: startsWith(matrix.os, 'macos')
        run: |
          go build .
          sh ./tools/create_mac_app.sh

      - name: Build DMG
        working-directory: ./src/github.com/useverto/desktop
        if: startsWith(matrix.os, 'macos')
        run: |
          yarn global add appdmg
          appdmg appdmg.json Verto.dmg

      - name: Build Windows app
        working-directory: ./src/github.com/useverto/desktop
        if: startsWith(matrix.os, 'windows')
        run: go build -ldflags="-H windowsgui" -o ./win/desktop.exe .
      
      - name: Build Windows MSI
        working-directory: ./src/github.com/useverto/desktop
        if: startsWith(matrix.os, 'windows')
        run: |
          $wixToolsetBinPath = ";C:\Program Files (x86)\WiX Toolset v3.11\bin;"
          $env:PATH = $env:PATH + $wixToolsetBinPath
          [Environment]::SetEnvironmentVariable("Path", $env:PATH, [EnvironmentVariableTarget]::Machine)
          candle.exe -out Verto.wixobj Verto.wxs
          light.exe -b ./win Verto.wixobj -out Verto.msi

      - uses: actions/upload-artifact@v2
        if: startsWith(matrix.os, 'ubuntu')
        with:
          name: verto-linux-x64.deb
          path: ./src/github.com/useverto/desktop/*.deb

      - uses: actions/upload-artifact@v2
        if: startsWith(matrix.os, 'macos')
        with:
          name: Verto.dmg
          path: ./src/github.com/useverto/desktop/*.dmg

      - uses: actions/upload-artifact@v2
        if: startsWith(matrix.os, 'macos')
        with:
          name: Verto.app
          path: ./src/github.com/useverto/desktop/*.app

      - uses: actions/upload-artifact@v2
        if: startsWith(matrix.os, 'windows')
        with:
          name: Verto.msi
          path: ./src/github.com/useverto/desktop/*.msi
