name: Ship

on:
  workflow_dispatch:

jobs:
  ship:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      - name: Setup repo
        uses: actions/checkout@v2
        with:
          submodules: true
          path: './src/github.com/useverto/desktop'

      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: 14.x

      - name: Setup go
        uses: actions/setup-go@v2
      
      - name: Install dependencies
        working-directory: ./src/github.com/useverto/desktop/verto
        run: |
          npm i -g yarn
          yarn

      - name: Build website source
        working-directory: ./src/github.com/useverto/desktop/verto
        run: | 
          yarn build
          yarn export

      - name: Install libwebkit
        if: startsWith(matrix.os, 'ubuntu')
        run: |
          sudo apt-get update
          sudo apt-get install libwebkit2gtk-4.0-dev
          
      
      - name: Install statik
        run: | 
          go get github.com/rakyll/statik          
      
      - name: Compile website
        run: go run ./src/github.com/useverto/desktop/fs/embed.go -src=${{ github.workspace }}/src/github.com/useverto/desktop/verto/__sapper__/export --dest=${{ github.workspace }}/src/github.com/useverto/desktop
      
      - name: Build desktop app
        working-directory: ./src/github.com/useverto/desktop
        if: startsWith(matrix.os, 'ubuntu')
        run: go build .
      
      - name: Build desktop app
        working-directory: ./src/github.com/useverto/desktop
        if: startsWith(matrix.os, 'macos')
        run: go build .

      - name: Build desktop app
        working-directory: ./src/github.com/useverto/desktop
        if: startsWith(matrix.os, 'macos')
        run: go build -ldflags="-H windowsgui" .
      
      - name: Zip linux release
        if: startsWith(matrix.os, 'ubuntu')
        working-directory: ./src/github.com/useverto/desktop
        run: |
          zip -r desktop-x64-linux.zip desktop README.md
      
      - name: Zip mac release
        if: startsWith(matrix.os, 'mac')
        working-directory: ./src/github.com/useverto/desktop
        run: |
          zip -r desktop-x64-macos.zip desktop README.md
      
      - name: Zip windows release
        if: startsWith(matrix.os, 'windows')
        working-directory: ./src/github.com/useverto/desktop
        run: |
          Compress-Archive -CompressionLevel Optimal -Force -Path desktop.exe, README.md -DestinationPath desktop-x64-windows.zip
      
      - name: Upload release artifacts
        uses: actions/upload-artifact@v2
        with:
          name: release
          path: |
            desktop-x64-linux.zip
            desktop-x64-macos.zip
            desktop-x64-windows.zip
  
        - name: Download artifacts
          uses: actions/download-artifact@v2

        - name: Release
          uses: ncipollo/release-action@v1
          with:
            tag: ${{ steps.version.outputs.tag }}
            name: ${{ steps.version.outputs.tag }}
            draft: true
            prerelease: false
            allowUpdates: true
            replacesArtifacts: true
            artifacts: "release/*"
            bodyFile: "notes/release.md"
            token: ${{ secrets.GITHUB_TOKEN }}